### ISSUE TITLE
Add VCF File to Contact Page (attached) 

### ISSUE THREAD

**Issue by andrewveklabs** [hennessyevan/VekLabs-1.0#29]
https://drive.google.com/file/d/19KhfMv6W_Zw5dPuc_4zWKjdqKQFPk_aK/view?usp=sharing

Link to downlod VCF file card.

**Comment by hennessyevan** [comment]
https://github.com/hennessyevan/VekLabs-1.0/commit/49dc020911be16b508621a8470a6686bdb84ebc2
