### ISSUE TITLE
Mobile: Text overlap work page

### ISSUE THREAD

**Issue by andrewveklabs** [hennessyevan/VekLabs-1.0#34]
![31740018_10215557635000167_8113435986580471808_n](https://user-images.githubusercontent.com/36556014/39545802-85237ef0-4e0f-11e8-9671-b72af8d28d52.jpg)

The title text overlaps for work place portfolio items.

**Comment by hennessyevan** [comment]
https://github.com/hennessyevan/VekLabs-1.0/commit/49dc020911be16b508621a8470a6686bdb84ebc2
