### ISSUE TITLE
Tab Selector - Work page - Ease in profolio items too slow

### ISSUE THREAD

**Issue by andrewveklabs** [hennessyevan/VekLabs-1.0#35]
![31517650_10215557634680159_6965541981711761408_n](https://user-images.githubusercontent.com/36556014/39545825-988fb710-4e0f-11e8-819c-ca941543d6f9.jpg)

Can you speed up the fade in animation for the work page items when you click "web" or "design" etc. 
The fade in animation is great, but a bit slow for mobile i think. 

Thanks man

**Comment by hennessyevan** [comment]
https://github.com/hennessyevan/VekLabs-1.0/commit/99d051179de187662e33a0f9f19ed73d677a0957
