### ISSUE TITLE
Case Study - Mobile - Body image size

### ISSUE THREAD

**Issue by andrewveklabs** [hennessyevan/VekLabs-1.0#37]
![31755254_10215557626519955_920803729421107200_n](https://user-images.githubusercontent.com/36556014/39545916-e861ef42-4e0f-11e8-927f-a33b9d2bb830.jpg)

The images in the body are too small. Can we make them full width with just a little padding left and right? 

Thanks.

**Comment by hennessyevan** [comment]
https://github.com/hennessyevan/VekLabs-1.0/commit/49dc020911be16b508621a8470a6686bdb84ebc2
